version: 2

multi-ecosystem-groups:
  everything:
    schedule:
      interval: weekly

updates:
  - package-ecosystem: github-actions
    cooldown:
      default-days: 7
    directory: /
    schedule:
      interval: daily
    patterns:
      - "*"
    multi-ecosystem-group: everything

  - package-ecosystem: nix
    cooldown:
      default-days: 7
    directory: /
    schedule:
      interval: daily
    patterns:
      - "*"
    multi-ecosystem-group: everything

  - package-ecosystem: nix
    cooldown:
      default-days: 7
    directory: /catornot-catornot-flakes
    schedule:
      interval: daily
    patterns:
      - "*"
    multi-ecosystem-group: everything
