services:
  northstar-dedicated:
    image: ghcr.io/asillyneko/northstar-dedicated
    network_mode: host
    tty: true
    stdin_open: true
    environment:
      - NS_PORT=37016
      - NSWRAP_NOWATCHDOGQUIT=1
      - NS_ARGUMENTS=-noshaderapi -nowindow
      - |
        NS_EXTRA_ARGUMENTS=
        +setplaylist tdm
        +mp_gamemode tdm
        +map mp_coliseum
        +ns_report_server_to_masterserver 0
        +ns_convar_test 1
        +ns_convar_test_url "https://northstar.tf"
        -enablechathooks
        -allowlocalhttp
        -multiple
        -nopakdedi
    volumes:
      - ./titanfall2-files-github-actions:/mnt/titanfall2:ro
      - ./Test-Build-Mod:/mnt/mods/Test-Build-Mod:ro
