name: Build Docker Image

on:
  push:
    paths: [ '.github/workflows/build.yml', 'Dockerfile', 'entrypoint.sh', 'northstar_version.sh', 'catornot-catornot-flakes/**' ]
  pull_request:
    paths: [ '.github/workflows/build.yml', 'Dockerfile', 'entrypoint.sh', 'northstar_version.sh', 'catornot-catornot-flakes/**' ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Get Northstar Version
        run: echo "NORTHSTAR_VERSION=$(grep 'export NORTHSTAR_VERSION=' northstar_version.sh | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.NORTHSTAR_VERSION }}
            type=sha

      - name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/northstar-dedicated.tar

      - name: Test Docker image
        env:
          RCLONE_CONFIG_CLOUDFLARE_TYPE: s3
          RCLONE_CONFIG_CLOUDFLARE_PROVIDER: Cloudflare
          RCLONE_CONFIG_CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
          RCLONE_CONFIG_CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_CLOUDFLARE_ENDPOINT: https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
        run: |
          cd .github/build
          sudo apt-get update && sudo apt-get install rclone -y
          rclone copy Cloudflare:titanfall2-files-github-actions titanfall2-files-github-actions
          docker load -i /tmp/northstar-dedicated.tar
          docker compose -f docker-compose.yml up -d
          timeout 60s python3 wait_for_ping.py || ( echo "Failed, timed out."; docker compose -f docker-compose.yml logs > /tmp/northstar_log.txt; docker compose -f .github/build/docker-compose.yml kill; exit 1 )
          docker compose -f docker-compose.yml kill
          docker compose -f docker-compose.yml logs > /tmp/northstar_log.txt

      - name: Upload log file
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-build-log
          path: /tmp/northstar_log.txt

      - name: Upload Docker image artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: northstar-dedicated
          path: /tmp/northstar-dedicated.tar

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha