name: ci

on:
  push:
    paths: ['.github/test-build/**', '.github/workflows/ci.yml', 'flake.nix', 'flake.lock', 'entrypoint.sh', 'northstar_version.sh', 'catornot-catornot-flakes/**']
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
        with:
          use-flakehub: false

      - name: Get Northstar version
        id: northstar_version
        run: echo "version=$(grep 'export NORTHSTAR_VERSION=' versions.sh | cut -d '=' -f2)" >> $GITHUB_OUTPUT

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.northstar_version.outputs.version }}
            type=sha

      - name: Build Docker image
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          nix build
          docker load -i result

          for tag in $(echo "$TAGS"); do
            docker tag ghcr.io/asillyneko/northstar-dedicated:latest "$tag"
          done

          docker save ghcr.io/asillyneko/northstar-dedicated -o /tmp/northstar-dedicated.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: /tmp/northstar-dedicated.tar
          archive: false

  test-build:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Download Docker image
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: northstar-dedicated.tar
          path: /tmp

      - name: Test Docker image
        run: |
          cd .github/test-build
          curl -fO https://titanfall2-files-github-actions.asillyneko.dev/titanfall2-files-github-actions.zip
          unzip titanfall2-files-github-actions.zip -d titanfall2-files-github-actions
          rm titanfall2-files-github-actions.zip
          docker load -i /tmp/northstar-dedicated.tar
          docker compose up -d
          timeout 2m python3 wait_for_ping.py || ( echo "Failed."; docker compose logs > /tmp/test-build-log.txt; exit 1 )
          docker compose logs > /tmp/test-build-log.txt
          docker compose kill

      - name: Upload log file
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: /tmp/test-build-log.txt
          archive: false

  release:
    needs: test-build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Download Docker image
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: northstar-dedicated.tar
          path: /tmp

      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Load and push Docker image
        env:
          Registry: ${{ env.REGISTRY }}
        run: |
          docker load -i /tmp/northstar-dedicated.tar
          docker push --all-tags ${Registry}/${IMAGE_NAME,,}
