name: ci

on:
  push:
    paths: [ '.github/build/**', '.github/workflows/ci.yml', 'flake.nix', 'flake.lock', 'entrypoint.sh', 'northstar_version.sh', 'catornot-catornot-flakes/**' ]
  pull_request:
    paths: [ '.github/build/**', '.github/workflows/ci.yml', 'flake.nix', 'flake.lock', 'entrypoint.sh', 'northstar_version.sh', 'catornot-catornot-flakes/**' ]
  workflow_call:
    inputs:
      ref:
        type: string
        default: ''
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Get Northstar version
        run: echo "NORTHSTAR_VERSION=$(grep 'export NORTHSTAR_VERSION=' northstar_version.sh | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.NORTHSTAR_VERSION }}
            type=sha

      - name: Build Docker image
        run: |
          nix build
          docker load -i result

          for tag in $(echo "${{ steps.meta.outputs.tags }}"); do
            docker tag ghcr.io/asillyneko/northstar-dedicated:latest "$tag"
          done

          docker save ghcr.io/asillyneko/northstar-dedicated -o /tmp/northstar-dedicated.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v7
        with:
          name: northstar-dedicated
          path: /tmp/northstar-dedicated.tar

  test-build:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Download Docker image
        uses: actions/download-artifact@v8
        with:
          name: northstar-dedicated
          path: /tmp

      - name: Test Docker image
        run: |
          cd .github/build
          curl -fO https://titanfall2-files-github-actions.asillyneko.dev/titanfall2-files-github-actions.zip
          unzip titanfall2-files-github-actions.zip -d titanfall2-files-github-actions
          rm titanfall2-files-github-actions.zip
          docker load -i /tmp/northstar-dedicated.tar
          docker compose up -d
          timeout 120s python3 wait_for_ping.py || ( echo "Failed."; docker compose logs > /tmp/test-build-log.txt; exit 1 )
          docker compose logs > /tmp/test-build-log.txt
          docker compose kill

      - name: Upload log file
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-build-log
          path: /tmp/test-build-log.txt

  release:
    needs: test-build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v8
        with:
          name: northstar-dedicated
          path: /tmp

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Load and push Docker image
        run: |
          docker load -i /tmp/northstar-dedicated.tar
          docker push --all-tags ${{ env.REGISTRY }}/${IMAGE_NAME,,}