name: dependabot-auto-merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-slim
    if: github.repository == 'ASillyNeko/Northstar-Dedicated' && github.event.pull_request.user.login == 'dependabot[bot]'

    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.NORTHSTAR_DEDICATED_CLIENT_ID }}
          private-key: ${{ secrets.NORTHSTAR_DEDICATED_PRIVATE_KEY }}

      - name: Enable auto merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
