version: 2

multi-ecosystem-groups:
  everything:
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    multi-ecosystem-group: "everything"

  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "daily"
    multi-ecosystem-group: "everything"

  - package-ecosystem: "nix"
    directory: "/catornot-catornot-flakes"
    schedule:
      interval: "daily"
    multi-ecosystem-group: "everything"
