name: update-northstar

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  get-northstar-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      no_changes: ${{ steps.git-check.outputs.no_changes }}
      ref: ${{ steps.commit.outputs.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Get Northstar Version
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/R2Northstar/Northstar/releases/latest > latest_release.json
          LATEST_VERSION=$(jq -r '.tag_name' latest_release.json)
          LATEST_VERSION_SHA256=$(jq -r '.assets[0].digest' latest_release.json | cut -d':' -f2)
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
          echo "LATEST_VERSION_SHA256=$LATEST_VERSION_SHA256" >> $GITHUB_ENV
          rm latest_release.json

      - name: Update northstar_version.sh
        run: |
          echo "export NORTHSTAR_VERSION=${LATEST_VERSION}" > northstar_version.sh
          echo "export NORTHSTAR_GITHUB_SHA256SUM=sha256:${LATEST_VERSION_SHA256}" >> northstar_version.sh

      - name: Check for Changes
        id: git-check
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push Changes
        id: commit
        if: steps.git-check.outputs.no_changes == 'false'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add northstar_version.sh
          git commit -m "Update Northstar version to ${LATEST_VERSION}"
          git push origin HEAD:main
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  ci:
    needs: get-northstar-version
    if: needs.get-northstar-version.outputs.no_changes == 'false'
    uses: ./.github/workflows/ci.yml
    with:
      ref: ${{ needs.get-northstar-version.outputs.ref }}
    secrets: inherit