name: update-northstar

on:
  push:
    paths: ['.github/workflows/update-northstar.yml']
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  get-northstar-version:
    if: github.repository == 'ASillyNeko/Northstar-Dedicated' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Get Northstar Version
        id: version
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/R2Northstar/Northstar/releases/latest > latest_release.json
          LATEST_VERSION=$(jq -r '.tag_name' latest_release.json)
          LATEST_VERSION_SHA256=$(jq -r '.assets[0].digest' latest_release.json | cut -d':' -f2)
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_OUTPUT
          echo "LATEST_VERSION_SHA256=$LATEST_VERSION_SHA256" >> $GITHUB_OUTPUT
          rm latest_release.json

      - name: Update northstar_version.sh
        env:
          NORTHSTAR_VERSION: ${{ steps.version.outputs.LATEST_VERSION }}
          NORTHSTAR_SHA256: ${{ steps.version.outputs.LATEST_VERSION_SHA256 }}
        run: |
          echo "export NORTHSTAR_VERSION=${NORTHSTAR_VERSION}" > northstar_version.sh
          echo "export NORTHSTAR_GITHUB_SHA256SUM=sha256:${NORTHSTAR_SHA256}" >> northstar_version.sh

      - name: Check for Changes
        id: git-check
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        id: cpr
        if: steps.git-check.outputs.no_changes == 'false'
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update Northstar version to ${{ steps.version.outputs.LATEST_VERSION }}"
          title: "Update Northstar version to ${{ steps.version.outputs.LATEST_VERSION }}"
          branch: "northstar/${{ steps.version.outputs.LATEST_VERSION }}"
          delete-branch: true

      - name: Enable auto merge
        if: steps.git-check.outputs.no_changes == 'false' && steps.cpr.outputs.pull-request-operation == 'created'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.cpr.outputs.pull-request-number }}
        run: gh pr merge --auto --squash "$PR_NUMBER"
