name: GitHub Actions Security Analysis

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['**']

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231 # v6
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@a16621b09c6db4281f81a93cb393b05dcd7b7165 # v0.5.3
